trigger:
- main
 
jobs:
- job: 'LintAndTestCode'
 
  pool:
    vmImage: ubuntu-latest
 
  strategy:
    matrix:
      R2022b:
        MATLAB_RELEASE: 'R2022b'
      R2023a:
        MATLAB_RELEASE: 'R2023a'
      R2023b:
        MATLAB_RELEASE: 'R2023b'
        
  variables: 
  - group: matlab-batch-license
 
  steps:
  - task: InstallMATLAB@0
    inputs:
      release: $(MATLAB_RELEASE)
    env:
      MATHWORKS_ACCOUNT: $(MATHWORKS_ACCOUNT)
      MATHWORKS_TOKEN: $(MATHWORKS_TOKEN)
 
  # This task Runs all the MATLAB and Simulink tests and generate variety of test artifacts. Check the documentation for all supported task parameters.
  - task: RunMATLABBuild@0
    inputs:
      tasks: test
    env:
      MATHWORKS_ACCOUNT: $(MATHWORKS_ACCOUNT)
      MATHWORKS_TOKEN: $(MATHWORKS_TOKEN)
       
