trigger:
- main


schedules:
- cron: '43/61 13/25 1/6 * *'
  displayName: Weekly-ish build
  branches:
    include:
    - main
    
jobs:
- job: 'RunMATLABBuild'
 
  pool:
    vmImage: $(PLATFORM)

  strategy:
    matrix:
      windows-MATLAB-R2022b:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2022b
      linux-MATLAB-R2022b:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2022b
      mac-MATLAB-R2022b:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2022b
        
      windows-MATLAB-R2023a:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2023a
      linux-MATLAB-R2023a:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2023a
      mac-MATLAB-R2023a:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2023a
        
      windows-MATLAB-R2023b:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2023b
      linux-MATLAB-R2023b:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2023b
      mac-MATLAB-R2023b:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2023b
        
  variables: 
  - group: matlab-batch-license
 
  steps:
  - task: Cache@2
    inputs:
      key: MATLAB-$(MATLAB_RELEASE)-$(PLATFORM)-20231028
      path: $(AGENT_TOOLSDIRECTORY)/MATLAB
  - task: InstallMATLAB@1
    inputs:
      release: $(MATLAB_RELEASE)
      products: >
        MATLAB
        MATLAB_Compiler
        MATLAB_Compiler_SDK
        Database_Toolbox
        Datafeed_Toolbox
        Econometrics_Toolbox
        Financial_Instruments_Toolbox
        Financial_Toolbox
        Optimization_Toolbox
        Parallel_Computing_Toolbox
        Statistics_and_Machine_Learning_Toolbox
 
  # This task Runs all the MATLAB and Simulink tests and generate variety of test artifacts. Check the documentation for all supported task parameters.
  - task: RunMATLABBuild@0
    inputs:
      tasks: test
    env:
      MATHWORKS_ACCOUNT: $(MATHWORKS_ACCOUNT)
      MATHWORKS_TOKEN: $(MATHWORKS_TOKEN)
       
