trigger:
- master

pool:
   name: Default

steps:
- task: RunMATLABTests@0
  inputs:
    testResultsJUnit: 'matlab-artifacts/testresults.xml'
    codeCoverageCobertura: 'matlab-artifacts/coverage.xml'
    sourceFolder: 'source'
