trigger:
- main
 
jobs:
- job: 'LintAndTestCode'
 
  pool:
    vmImage: $(PLATFORM)

  strategy:
    matrix:
      windows-MATLAB-R2022b:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2022b
      linux-MATLAB-R2022b:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2022b
      mac-MATLAB-R2023a:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2022b
        
      windows-MATLAB-R2023a:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2023a
      linux-MATLAB-R2023a:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2023a
      mac-MATLAB-R2023a:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2023a
        
      windows-MATLAB-R2023b:
        PLATFORM: 'windows-latest'
        MATLAB_RELEASE: R2023b
      linux-MATLAB-R2023b:
        PLATFORM: 'ubuntu-latest'
        MATLAB_RELEASE: R2023b
      mac-MATLAB-R2023b:
        PLATFORM: 'macOS-latest'
        MATLAB_RELEASE: R2023b
        
  variables: 
  - group: matlab-batch-license
 
  steps:
  - task: Cache@2
    inputs:
      key: MATLAB-$(MATLAB_RELEASE)-$(PLATFORM)
      path: $(AGENT_TOOLSDIRECTORY)/MATLAB
  - task: InstallMATLAB@1
    inputs:
      release: $(MATLAB_RELEASE)
 
  # This task Runs all the MATLAB and Simulink tests and generate variety of test artifacts. Check the documentation for all supported task parameters.
  - task: RunMATLABBuild@0
    inputs:
      tasks: test
    env:
      MATHWORKS_ACCOUNT: $(MATHWORKS_ACCOUNT)
      MATHWORKS_TOKEN: $(MATHWORKS_TOKEN)
       
