# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Build

# Controls when the action will run. 
on: 
  push:                       # Runs on push events
  pull_request:               # Runs on pull requests
  workflow_dispatch:          # Allows you to run this workflow manually from the Actions tab
    
jobs:
  # This workflow contains a single job called "build"


  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        release: [R2022b, R2023a]
        
    # The type of runner that the job will run on
    runs-on: ${{ matrix.platform }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.platform }}-${{ matrix.release }}
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta

      # Runs a set of commands using the runners shell
      - name: Generate mex files & run tests
        uses: matlab-actions/run-build@v1
        with: 
          tasks: test
      - name: Upload Mex Files
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: Mex-Artifacts-${{ matrix.platform }}-${{ matrix.release }}
          # A file, directory or wildcard pattern that describes what to upload
          path: toolbox/**/*.mex*64

          
  create-toolbox:
    needs: test 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ubuntu-latest::R2022b

      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta

      - name: Download artifacts
        if: ${{ always() }}
        uses: actions/download-artifact@v3
        with:
          path: toolbox
          
      - name: Move artifacts & delete artifact folders
        run: mv Mex-Artifacts-*-R2022b/**/*.mex*64 . & rmdir Mex-Artifacts-*
        working-directory: toolbox

      # Runs a set of commands using the runners shell
      - name: Run toolbox build
        uses: matlab-actions/run-build@v1
        with: 
          tasks: toolbox
     
      - name: Upload Toolbox
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: Toolbox Package
          # A file, directory or wildcard pattern that describes what to upload
          path: release/Mass-Spring-Damper.mltbx

  
